services:
  - type: web
    name: bytebase
    region: ohio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: PG_URL
        fromDatabase:
          name: bytebase-metadb
          property: connectionString
databases:
  - name: bytebase-metadb
    region: ohio
    plan: free
    postgresMajorVersion: 15
